build_script:
    - pwsh: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode -Version 2.0
          ./lint.ps1
          ./build.ps1
environment:
    TOKEN:
        secure: yGn2bm33EtB8/7oX0N/UCk0akm3mWZ3yU2mz7Dl9Ptd8iVuN7wzQtNSCF+V8TMgm
image: Visual Studio 2019 Preview
install:
    - pwsh: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode -Version 2.0
          npm install markdownlint-cli -g
          choco install docfx -y
on_success:
    - pwsh: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode -Version 2.0
          git config --global credential.helper store
          Add-Content "$HOME\.git-credentials" "https://$($Env:TOKEN):x-oauth-basic@github.com`n"
          git config --global user.email "alex@alexrp.com"
          git config --global user.name "AppVeyor"
          $sha = git rev-parse HEAD -q --verify
          git checkout origin/master -b master
          git rm "*" -fr
          git checkout HEAD -- .gitattributes .nojekyll CNAME
          Move-Item build/* .
          Remove-Item build, darkfx, obj -Force -Recurse
          git add -A
          git commit -m "CI: Deploy $sha."
          git push origin master
          git checkout source
pull_requests:
    do_not_increment_build_number: true
skip_tags: true
