# Reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI
on:
    push:
    pull_request:
        types:
            - edited
            - opened
            - reopened
            - synchronize
defaults:
    run:
        shell: bash
jobs:
    ci:
        runs-on: windows-latest
        steps:
            - uses: xt0rted/markdownlint-problem-matcher@v1.0.0
            - name: Clone repository
              uses: actions/checkout@v2.3.4
            - name: Fetch full history
              run: |
                  git fetch origin --unshallow
            - name: Set up Node.js
              uses: actions/setup-node@v2.1.2
            - name: Install dependencies
              run: |
                  npm install markdownlint-cli@0.23.2 -g
                  choco install docfx --version 2.56.2 -y
                  choco install wkhtmltopdf --version 0.12.6 -y
            - name: Lint Markdown files
              run: |
                  ./lint.ps1
            - name: Build website
              run: |
                  ./build.ps1
            - name: Deploy website
              if: github.event_name == 'push' && github.ref == 'refs/heads/master'
              run: |
                  git config --global user.name github-actions
                  git config --global user.email bot@flare-lang.org
                  sha=$(git show -s --format=%H)
                  git checkout origin/live -b live
                  git rm "*" -fr
                  git checkout HEAD -- .gitattributes .nojekyll CNAME
                  mv build/web/* .
                  rm build obj -fr
                  git add -A
                  git commit -m "CI: Deploy $sha." || exit 0
                  git push origin live
            - name: Notify Discord
              if: failure() && github.event_name == 'push' && github.repository == 'flare-lang/flare-lang.github.io'
              uses: sarisia/actions-status-discord@v1.8.0
              with:
                  webhook: ${{ secrets.DISCORD_BUILDS_WEBHOOK }}
