name: CI
on:
    push:
    pull_request:
        types:
            - edited
            - opened
            - reopened
            - synchronize
jobs:
    ci:
        runs-on: windows-latest
        steps:
            - uses: xt0rted/markdownlint-problem-matcher@v1
            - name: Clone repository
              uses: actions/checkout@v2.3.2
            - name: Fetch full history
              shell: pwsh
              run: |
                  git fetch origin --unshallow
            - name: Install dependencies
              shell: pwsh
              run: |
                  npm install markdownlint-cli -g
                  choco install docfx -y
            - name: Lint Markdown files
              shell: pwsh
              run: |
                  ./lint.ps1
            - name: Build website
              shell: pwsh
              run: |
                  ./build.ps1
            - name: Deploy website
              if: github.event_name == 'push'
              shell: pwsh
              run: |
                  $ErrorActionPreference = "Continue"
                  git config --global user.name "github-actions"
                  git config --global user.email "alex@alexrp.com"
                  $sha = git rev-parse HEAD -q --verify
                  echo "$? Source commit SHA is $sha"
                  git checkout origin/live -b live
                  echo "$? Removing old files"
                  git rm "*" -fr
                  echo "$? Restoring special files"
                  git checkout HEAD -- .gitattributes .nojekyll CNAME
                  echo "$? Moving built files"
                  Move-Item build/* .
                  echo "$?Removing build directories"
                  Remove-Item build, obj -Force -Recurse
                  echo "$? Adding changes"
                  git add -A
                  echo "$? Committing changes"
                  git commit -m "CI: Deploy $sha."
                  echo "$? Pushing changes"
                  git push origin live
                  echo "$? Switching back to master"
                  git checkout master
